name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1
      - name: Install dependencies
        run: npm install
      - name: Compile TypeScript
        run: tsc
      - name: Prune Dev Dependencies
        run: |
          npm prune --production
          rm -rf ./src
      - name: Deploy to AWS Lambda
        run: |
          zip -r deploy.zip ./*
          aws lambda update-function-code --function-name=wordle-api --zip-file=fileb://deploy.zip
